### ISSUE TITLE
怎么导出

### ISSUE THREAD

**Issue by wangzheooo** [redisviewer/RedisViewer#1]

**Comment by redisviewer** [comment]
![image](https://user-images.githubusercontent.com/12822830/218398563-dfb68368-f933-4d4a-a6e0-c8f4bc90903e.png)

详情右上角这里

**Comment by wangzheooo** [comment]
可以导出整个库吗

**Comment by redisviewer** [comment]
整个库的话找找redis官方的命令吧
http://redis.cn/commands.html
