### ISSUE TITLE
集群环境链接失败

### ISSUE THREAD

**Issue by zcccust** [redisviewer/RedisViewer#3]
测试链接时提出成功，点击列表时提示链接失败。
![1](https://github.com/redisviewer/RedisViewer/assets/8574876/f83ba1af-506c-4f27-9a4f-23db973eb0b7)
![2](https://github.com/redisviewer/RedisViewer/assets/8574876/e1ced252-0a7a-4d67-a135-d4b4e133f569)
![3](https://github.com/redisviewer/RedisViewer/assets/8574876/bd2cdf57-a27f-462f-9198-4e4044c750f7)

**Comment by redisviewer** [comment]
`C:\Users\Administrator\.redis_viewer\logs\redisviewer.20231213.log `
上传日志文件看看
另外redisviewer版本号是2.3.2吗？

**Comment by zcccust** [comment]
版本是2.3.2
通过您提供的日志路径，定位到问题了。
是因为我们环境，只可以联通到redis集群的主节点，到从节点网络不通导致的。

**Comment by redisviewer** [comment]
测试连接测试的是输入的节点，一律是单点PING测试，

真正连接的时候还有一个测试，这时候会判断是否集群，
集群客户端PING测试这里没有通过

**Comment by redisviewer** [comment]
> 版本是2.3.2 通过您提供的日志路径，定位到问题了。 是因为我们环境，只可以联通到redis集群的主节点，到从节点网络不通导致的。

网络上实在有问题连不上的话，你可以考虑ssh，或者远程模式
ssh的话网络统一会走ssh连接的这个点
远程模式的话，本地客户端会访问远程客户端，真正访问redis服务器的是远程的客户端，可以看看介绍
