### ISSUE TITLE
集群模式无法切换数据库

### ISSUE THREAD

**Issue by chenwj93** [redisviewer/RedisViewer#4]
![image](https://github.com/redisviewer/RedisViewer/assets/28521021/ff541609-b331-48e5-b684-7876dbaffdbb)
![image](https://github.com/redisviewer/RedisViewer/assets/28521021/e855ffb2-6416-46d7-b404-164c120ca298)
**keySpace信息中可以拿到数据库列表，命令行也可以切换，但是ui操作db列表中没有其他库**

**Comment by redisviewer** [comment]
你确定你这个是集群模式吗？  
执行cluster info
执行info
我看下

**Comment by redisviewer** [comment]
<img width="930" alt="image" src="https://github.com/redisviewer/RedisViewer/assets/12822830/d783a307-4d67-48ef-a47a-ca48ae0671ba">

确定你这个是集群模式吗？
集群啥时候支持多db了。。。
截图看看你这里

**Comment by redisviewer** [comment]
没有后续反馈，手动关闭

**Comment by chenwj93** [comment]
![image](https://github.com/redisviewer/RedisViewer/assets/28521021/ae2aa61f-40ae-43b0-8e66-2a0ad2862aea)
不好意思，没办法先用了RDM，没上来看了；
这个是用的阿里云的rds
