### ISSUE TITLE
显示的数据库只有15个，太少了，没法切换

### ISSUE THREAD

**Issue by zt80hou** [redisviewer/RedisViewer#5]
![image](https://github.com/redisviewer/RedisViewer/assets/10629437/53b1d77f-9194-4307-9182-c2e4f2434f91)

**Comment by redisviewer** [comment]
db 0 ~ 15，总共16个没有问题。
无法切换的错误信息有吗？

或者在这里日志文件找一下错误
~/.redis_viewer/logs/redismanager.log

**Comment by redisviewer** [comment]
没有后续反馈，手动关闭
