### ISSUE TITLE
连接数据异常

### ISSUE THREAD

**Issue by cxkj2403** [redisviewer/RedisViewer#6]
![1710840610124](https://github.com/redisviewer/RedisViewer/assets/163227667/dff07f0a-1b10-4ab3-8a09-0a84c7263a87)

连接时报错

**Comment by redisviewer** [comment]
1.4、1.5版本升级2.x版本，需要先删除用户目录下.redis_viewer文件夹，例如：

C:\Users\Administrator.redis_viewer
/home/zhang3/.redis_viewer
