### ISSUE TITLE
连接阿里云RDS时，自动判定为集群模式，导致无法切换库

### ISSUE THREAD

**Issue by chenwj93** [redisviewer/RedisViewer#7]
![image](https://github.com/redisviewer/RedisViewer/assets/28521021/ae2aa61f-40ae-43b0-8e66-2a0ad2862aea)
https://github.com/redisviewer/RedisViewer/issues/4 续这个issue
不好意思，没办法先用了RDM，没上来看了；
这个是用的阿里云的rds
另外就是我用其他工具连接时：手动选择单节点模式连接，也是可以切换库的；但是redisviewer改不了这个模式

**Comment by redisviewer** [comment]
明白你的意思了，他本是单机redis，自动识别成集群了
考虑下个版本把集群模式开关放开，让纯手动配置，应该能解决这个问题

**Comment by chenwj93** [comment]
另外那个#5 issue说显示的数据库太少我这边可能也有这个问题，阿里云rds的数据库好像是挺多的，你看我上面的图里有256个；我用RDM打开至少能显示20个

**Comment by redisviewer** [comment]
> 另外那个#5 issue说显示的数据库太少我这边可能也有这个问题，阿里云rds的数据库好像是挺多的，你看我上面的图里有256个；我用RDM打开至少能显示20个

你阿里云rds上面实际上是个单机redis是吧

**Comment by redisviewer** [comment]
> 另外那个#5 issue说显示的数据库太少我这边可能也有这个问题，阿里云rds的数据库好像是挺多的，你看我上面的图里有256个；我用RDM打开至少能显示20个

[https://github.com/redisviewer/RedisViewer/releases/tag/v2.4.1](https://github.com/redisviewer/RedisViewer/releases/tag/v2.4.1)
新版本试一下吧，升级了框架，同时不在自动配置是否集群，手动配置

**Comment by redisviewer** [comment]
> 另外那个#5 issue说显示的数据库太少我这边可能也有这个问题，阿里云rds的数据库好像是挺多的，你看我上面的图里有256个；我用RDM打开至少能显示20个

没用过这个，我想想看有没有啥办法
rds可以支持这么多库....

**Comment by redisviewer** [comment]
![图片](https://github.com/redisviewer/RedisViewer/assets/12822830/b5df5bc1-3d9f-4eb7-aaf6-1d0bb5d3ad61)

暂时可以先使用命令选择db，你在控制台手动输入
`select 255`
完了再去点界面的刷新按钮，这样可以跳过界面上的db选择器，先试试应该是能用了


后续的话得连接一个阿里云rds实例，才好排查，针对性的解决这个问题，如果你也觉得合适的话...

**Comment by chenwj93** [comment]
好的，谢谢

**Comment by redisviewer** [comment]
> 好的，谢谢

不客气，麻烦截图反馈看一下，这边没有rds实例可以试

**Comment by chenwj93** [comment]
![image](https://github.com/redisviewer/RedisViewer/assets/28521021/e0aac321-22e2-4e27-baa4-ccb9e1e37dfe)

可以了，通过命令可以切到16号之后的库

**Comment by redisviewer** [comment]
> 好的，谢谢

其实db选择器做到与实际一致
就看是否介意这边连接调试一下这边阿里云rds，
如果合适的话可以，请把链接方法发送到邮箱124410675@qq.com
介意也可以理解~

**Comment by chenwj93** [comment]
暂时不行哈，这是客户的环境，抱歉
